version: '3.1'

services:
  db:
    image: mysql:latest
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: task_manager
      MYSQL_USER: sol
      MYSQL_PASSWORD: password

  app:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      DB_USER: sol
      DB_PASSWORD: password
      DB_HOST: db
      DB_PORT: 3306
      DB_NAME: task_manager
